language: node_js
branches:
  except:
    - debug
node_js:
  - 4.0
  - 4.2
  - 5.0
  - 6.8
  - 7.9
  - 8.6
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
